# fly.toml app configuration file generated for nextchat-z on 2025-04-23T18:49:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nextchat-z'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 4096
